version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    networks:
      - chirpstack-backend
    volumes:
      - ./config/chirpstack/network-server.toml:/etc/chirpstack-network-server/chirpstack-network-server.toml

  chirpstack:
    image: chirpstack/chirpstack-application-server:3
    networks:
      - cs-tb-bridge-ntw
      - chirpstack-frontend
      - chirpstack-backend
    ports:
      - 8080:8080
    volumes:
      - ./config/chirpstack/application-server.toml:/etc/chirpstack-application-server/chirpstack-application-server.toml

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    networks:
      - chirpstack-backend
    ports:
      - 1700:1700/udp
    volumes:
      - ./config/chirpstack/gateway-bridge.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml

  chirpstack-geolocation-server:
    networks:
      - chirpstack-backend
    image: chirpstack/chirpstack-geolocation-server:3
    volumes:
      - ./config/chirpstack/geolocation-server.toml:/etc/chirpstack-geolocation-server/chirpstack-geolocation-server.toml

  redis:
    image: redis:5-alpine
    networks:
      - chirpstack-backend
    volumes:
      - cs-redis-data:/data

  mosquitto:
    image: eclipse-mosquitto:1.6
    networks:
      - chirpstack-backend
    ports:
      - 1883:1883
  
  thingsboard:
    image: ivan28823/thingsboard:v3.2
    networks:
      - cs-tb-bridge-ntw
      - thingsboard-frontend
      - thingsboard-backend
    environment:
      - PG_HOST=postgresql
      - PG_USER=thingsboard
      - PG_PASS=thingsboard-passwd
    ports:
      - 30010:9090
      - 1884:1883
      - 5683:5683/udp
    volumes:
      - tb-data:/data
  
  postgresql:
    image: postgres:12-alpine
    networks:
      - chirpstack-backend
      - thingsboard-backend
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./config/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
   
volumes:
  tb-data:
  postgres-data:
  cs-redis-data:

networks:
  cs-tb-bridge-ntw:
  chirpstack-frontend:
  chirpstack-backend:
  thingsboard-frontend:
  thingsboard-backend:
    
