version: "3"

services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    networks:
      - reverse-proxy-ntw
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro    

  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./config/chirpstack/network-server.toml:/etc/chirpstack-network-server/chirpstack-network-server.toml

  chirpstack:
    image: chirpstack/chirpstack-application-server:3
    networks:
      - reverse-proxy-ntw
      - chirpstack-frontend
      - chirpstack-backend
    environment:
      - VIRTUAL_HOST=chirpstack.*
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./config/chirpstack/application-server.toml:/etc/chirpstack-application-server/chirpstack-application-server.toml

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    networks:
      - chirpstack-backend
    ports:
      - 1700:1700/udp
    volumes:
      - ./config/chirpstack/gateway-bridge.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml

  chirpstack-geolocation-server:
    networks:
      - chirpstack-backend
    image: chirpstack/chirpstack-geolocation-server:3
    volumes:
      - ./config/chirpstack/geolocation-server.toml:/etc/chirpstack-geolocation-server/chirpstack-geolocation-server.toml

  postgresql:
    image: postgres:9.6-alpine
    networks:
      - chirpstack-backend
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./config/postgresql/initdb:/docker-entrypoint-initdb.d
      - cs-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    networks:
      - chirpstack-backend
    volumes:
      - cs-redis-data:/data

  mosquitto:
    image: eclipse-mosquitto:1.6
    networks:
      - chirpstack-backend
    ports:
      - 1883:1883
  
  thingsboard:
    image: ivan28823/thingsboard:2.4.3
    networks:
      - reverse-proxy-ntw
      - thingsboard-frontend
      - thingsboard-backend
    environment:
      - VIRTUAL_HOST=thingsboard.*
      - VIRTUAL_PORT=9090
      - PG_HOST=tb-postgres
      - PG_USER=thingsboard
      - PG_PASS=verysecret
    ports:
      - 9090:9090
      - 1884:1883
      - 5683:5683/udp
    volumes:
      - tb-data:/data
    
  tb-postgres:
    image: postgres:12-alpine
    networks:
      - thingsboard-backend
    environment:
      - POSTGRES_USER=thingsboard
      - POSTGRES_DB=thingsboard 
      - POSTGRES_PASSWORD=verysecret
    volumes:
      - tb-postgres-data:/var/lib/postgresql/data

volumes:
  tb-data:
  tb-postgres-data:
  cs-postgres-data:
  cs-redis-data:

networks:
  reverse-proxy-ntw:
  chirpstack-frontend:
  chirpstack-backend:
  thingsboard-frontend:
  thingsboard-backend:
    
