## See https://www.chirpstack.io/network-server/install/config/ for a full
# configuration example and documentation.
#
# This file is for the EU868 band. See the examples/ folder for more
# configuration examples.

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable"

[redis]
url="redis://redis:6379"

[network_server]
net_id="010203"

[network_server.band]
name="US_902_928"

  [network_server.network_settings]
  enabled_uplink_channels=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

[network_server.gateway.backend.mqtt]
server="tcp://mosquitto:1883"

[join_server.default]
server="http://chirpstack:8003"

[geolocation_server]
server="chirpstack-geolocation-server:8005" 

